//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proect.ADDO
{
    using System;
    using System.Collections.Generic;
    
    public partial class goods_Salesman
    {
        public int id { get; set; }
        public int id_Goods { get; set; }
        public int id_Salesman { get; set; }
        public int Kol_goods { get; set; }
        public string summa { get; set; }
        public System.DateTime Date_1 { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual Salesman Salesman { get; set; }
    }
}
